# Generated by Django 3.2.6 on 2021-11-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('Recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('Recipe_name', models.CharField(max_length=100)),
                ('Recipe_description', models.TextField()),
                ('Recipe_type', models.CharField(max_length=100)),
                ('Recipe_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Recipe_prep_details',
            fields=[
                ('Recipe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipe.recipe')),
                ('preparation_time', models.DurationField()),
                ('num_of_servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
            options={
                'db_table': 'recipe_prep_details',
            },
        ),
    ]
