# Generated by Django 3.2.6 on 2021-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_prep_details',
            old_name='Recipe_id',
            new_name='Recipe',
        ),
    ]
