# Generated by Django 3.2.6 on 2021-11-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_recipe_id_recipe_prep_details_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutri_content',
            fields=[
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipe.recipe')),
                ('calories_per_serving', models.CharField(max_length=100)),
                ('carbs', models.CharField(max_length=100)),
                ('proteins', models.CharField(max_length=100)),
                ('saturated_fats', models.CharField(max_length=100)),
                ('trans_fats', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nutri_content',
            },
        ),
        migrations.AlterField(
            model_name='recipe_prep_details',
            name='preparation_time',
            field=models.CharField(max_length=100),
        ),
    ]
