# Generated by Django 3.2.6 on 2021-11-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.FileField(default='default.jpg', upload_to='recipe_imgs'),
        ),
    ]
