# Generated by Django 3.2.6 on 2021-11-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_nutri_content_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='recipe_imgs'),
        ),
    ]
