# Generated by Django 3.2.6 on 2021-11-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img',
        ),
    ]
