# Generated by Django 3.2.6 on 2021-11-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
