# Generated by Django 3.2.6 on 2021-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_alter_feedback_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='recipe_imgs/default.jpg', upload_to='recipe_imgs'),
        ),
    ]
