# Generated by Django 3.2.6 on 2021-11-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='recipe_default.jpg', upload_to='recipe_imgs'),
        ),
    ]
