# Generated by Django 3.2.6 on 2021-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_auto_20211112_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Egg', 'Egg'), ('Vegan', 'Vegan')], default='Veg', max_length=100),
        ),
    ]
